apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
      name: webhook
    - port: 8443
      targetPort: 8443
      name: metrics
  selector:
    control-plane: controller-manager