# permissions for end users to view schedulinggatesorderings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduling-gates-coordinator
    app.kubernetes.io/managed-by: kustomize
  name: schedulinggatesordering-viewer-role
rules:
- apiGroups:
  - ksgc.outrigger.sh
  resources:
  - schedulinggatesorderings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ksgc.outrigger.sh
  resources:
  - schedulinggatesorderings/status
  verbs:
  - get
