//go:build !ignore_autogenerated

/*
Copyright 2025 outrigger-project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingGatesOrdering) DeepCopyInto(out *SchedulingGatesOrdering) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingGatesOrdering.
func (in *SchedulingGatesOrdering) DeepCopy() *SchedulingGatesOrdering {
	if in == nil {
		return nil
	}
	out := new(SchedulingGatesOrdering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingGatesOrdering) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingGatesOrderingList) DeepCopyInto(out *SchedulingGatesOrderingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SchedulingGatesOrdering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingGatesOrderingList.
func (in *SchedulingGatesOrderingList) DeepCopy() *SchedulingGatesOrderingList {
	if in == nil {
		return nil
	}
	out := new(SchedulingGatesOrderingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingGatesOrderingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingGatesOrderingSpec) DeepCopyInto(out *SchedulingGatesOrderingSpec) {
	*out = *in
	if in.SchedulingGates != nil {
		in, out := &in.SchedulingGates, &out.SchedulingGates
		*out = make([]v1.PodSchedulingGate, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingGatesOrderingSpec.
func (in *SchedulingGatesOrderingSpec) DeepCopy() *SchedulingGatesOrderingSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingGatesOrderingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingGatesOrderingStatus) DeepCopyInto(out *SchedulingGatesOrderingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingGatesOrderingStatus.
func (in *SchedulingGatesOrderingStatus) DeepCopy() *SchedulingGatesOrderingStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulingGatesOrderingStatus)
	in.DeepCopyInto(out)
	return out
}
